export * from 'mdx-deck/dist/components'

export { default as Airmail } from './air-mail'
export { default as Banner } from './banner'
export { default as Box } from './box'
export { default as Fit } from './fit'
export { default as FITC } from './fitc'
export { default as Grid } from './grid'
export { default as Link } from './link'
export { default as Image } from './image'
export { default as Social } from './social'
